import { Router } from "express";
import * as repo from "../db/repo.js";
import * as gemini from "../services/gemini.js";
import * as postiz from "../services/postiz.js";
import { config } from "../config.js";
import { requireAuth, optionalAuth } from "../lib/auth.js";
import { pick, LAST_NAMES } from "../lib/util.js";

const router = Router();

const asyncH = (fn) => (req, res) =>
  Promise.resolve(fn(req, res)).catch((err) => {
    console.error(`[generate] ${req.method} ${req.originalUrl} failed:`, err);
    res
      .status(500)
      .json({ ok: false, error: err?.message || String(err) || "internal error" });
  });

// Public: generate an influencer image from a text prompt.
router.post(
  "/influencer-image",
  asyncH(async (req, res) => {
    const prompt = String(req.body.prompt || "").trim();
    if (!prompt) {
      return res.status(400).json({ ok: false, error: "prompt is required" });
    }
    if (!gemini.isConfigured()) {
      return res
        .status(503)
        .json({ ok: false, error: "image generation is not configured" });
    }

    const image = await gemini.generateInfluencerImage({ prompt });
    res.json({ ok: true, prompt, imageUrl: image.url });
  })
);

// Public: from a creation brief, design a character and render its portrait. The
// persona/content plan and portrait are generated by Gemini. The portrait uses
// Nano Banana Pro directly through the Gemini API.
router.post(
  "/onboarding-character",
  asyncH(async (req, res) => {
    const answers = req.body.answers;
    if (!answers || typeof answers !== "object" || Array.isArray(answers)) {
      return res
        .status(400)
        .json({ ok: false, error: "answers object is required" });
    }
    if (!gemini.isConfigured()) {
      return res
        .status(503)
        .json({ ok: false, error: "character generation is not configured" });
    }

    // Per-request randomness so repeated identical answers (e.g. always asking
    // for "Stacy") don't collapse to the same surname. The surname is picked
    // from a real list and suggested to the model.
    const suggestedLastName = pick(LAST_NAMES);

    const character = await gemini.designOnboardingCharacter({ answers, suggestedLastName });

    const imagePrompt =
      character.imagePrompt ||
      [character.appearance, character.aesthetic].filter(Boolean).join(". ") ||
      character.displayName;

    const image = await gemini.generateInfluencerImage({ prompt: imagePrompt });

    res.json({ ok: true, character, imageUrl: image.url });
  })
);

// Public: generate a brand-new, varied Instagram post (image + caption +
// hashtags) for an existing persona. Designed to be called repeatedly from an
// influencer's detail page; each call produces a fresh, natural-feeling post.
// The response includes a ready-to-paste block so it can be dropped straight
// into Instagram until Browser Use auto-posting is wired up.
router.post(
  "/post",
  optionalAuth,
  asyncH(async (req, res) => {
    // The persona shape we store on a saved generation (Character). Older saved
    // rows may have an empty persona, so fall back to the prompt text.
    const persona =
      req.body.persona && typeof req.body.persona === "object"
        ? req.body.persona
        : {};
    const fallbackPrompt = String(req.body.prompt || "").trim();
    // When the panel passes an owned influencerId, the post is persisted to that
    // influencer's content history.
    const influencerId = req.body.influencerId || null;

    const hasPersona = persona && Object.keys(persona).length > 0;
    if (!hasPersona && !fallbackPrompt) {
      return res
        .status(400)
        .json({ ok: false, error: "persona or prompt is required" });
    }
    if (!gemini.isConfigured()) {
      return res
        .status(503)
        .json({ ok: false, error: "post generation is not configured" });
    }

    // If we only have a prompt (no structured persona), build a minimal persona
    // so the generator still has something on-brand to work from.
    const effectivePersona = hasPersona
      ? persona
      : {
          displayName: "Influencer",
          niche: fallbackPrompt,
          personality: fallbackPrompt,
          appearance: fallbackPrompt,
          aesthetic: fallbackPrompt,
        };

    // If the caller owns this influencer, load it now so we can feed its saved
    // profile photo to the image model as a subject reference — this is what
    // keeps the post looking like the same person as the profile.
    let ownedInfluencer = null;
    if (influencerId && req.user) {
      const inf = await repo.influencers.get(influencerId);
      if (inf && inf.user_id === req.user.id) ownedInfluencer = inf;
    }

    const post = await gemini.generatePostContent({ persona: effectivePersona });

    // Render the post image from the scene prompt through Gemini Nano Banana.
    const imagePrompt =
      post.imagePrompt ||
      effectivePersona.imagePrompt ||
      [effectivePersona.appearance, effectivePersona.aesthetic]
        .filter(Boolean)
        .join(". ") ||
      fallbackPrompt;

    const image = await gemini.generateInfluencerImage({
      prompt: imagePrompt,
      influencerId: ownedInfluencer?.id,
      label: "post",
      frameAsSelfie: post.shotType !== "scene",
      referenceImage: ownedInfluencer?.image_url || null,
    });

    const hashtagLine = post.hashtags.map((h) => `#${h}`).join(" ");
    // A single block that's trivial to copy and paste into Instagram: caption,
    // a blank line, then the hashtags.
    const copyText = [post.caption, hashtagLine].filter(Boolean).join("\n\n");

    // Persist to the influencer's content history when the caller owns it. The
    // image URL is stored in image_paths (no video for an image post); status
    // "ready" means it's generated and ready to publish. Best-effort: a save
    // failure never blocks returning the generated post to the user.
    let contentId = null;
    if (ownedInfluencer) {
      try {
        const item = await repo.content.create({
          influencerId,
          topic: post.title || null,
          status: "ready",
        });
        await repo.content.update(item.id, {
          title: post.title || null,
          caption: post.caption,
          hashtags: post.hashtags || [],
          image_paths: [image.url],
          meta: { altText: post.altText, imagePrompt, source: "quick-post" },
        });
        contentId = item.id;
      } catch {
        /* non-fatal: still return the generated post below */
      }
    }

    res.json({
      ok: true,
      contentId,
      imageUrl: image.url,
      caption: post.caption,
      hashtags: post.hashtags,
      hashtagLine,
      altText: post.altText,
      imagePrompt,
      copyText,
    });
  })
);

// Shared ownership/config guard for the preview + publish endpoints. Returns
// the loaded influencer, or null after sending an error response.
async function loadInfluencerForPost(req, res, { requirePublic = false } = {}) {
  const influencerId = req.body.influencerId;
  if (!influencerId) {
    res.status(400).json({ ok: false, error: "influencerId is required" });
    return null;
  }
  if (!gemini.isConfigured()) {
    res
      .status(503)
      .json({ ok: false, error: "image generation is not configured (GEMINI_API_KEY)" });
    return null;
  }
  if (requirePublic) {
    if (!postiz.isConfigured()) {
      res
        .status(503)
        .json({ ok: false, error: "Postiz is not configured (POSTIZ_API_KEY)" });
      return null;
    }
    if (!config.publicBaseUrl) {
      res.status(503).json({
        ok: false,
        error: "PUBLIC_BASE_URL is required so Postiz can fetch generated images",
      });
      return null;
    }
  }
  const inf = await repo.influencers.get(influencerId);
  if (!inf) {
    res.status(404).json({ ok: false, error: "influencer not found" });
    return null;
  }
  if (inf.user_id && inf.user_id !== req.user.id) {
    res.status(403).json({ ok: false, error: "forbidden" });
    return null;
  }
  return inf;
}

// Auth required: generate a post (image + caption) for an influencer and SAVE IT
// AS A DRAFT for review — does NOT publish. The photo is rendered with Gemini
// Nano Banana, the caption + hashtags are built from the persona. The draft is
// stored in the influencer's content history with status "ready" and its id is
// returned so the client can publish it after the user reviews it.
router.post(
  "/post-preview",
  requireAuth,
  asyncH(async (req, res) => {
    const inf = await loadInfluencerForPost(req, res);
    if (!inf) return;

    const persona = inf.persona && typeof inf.persona === "object" ? inf.persona : {};

    // Build caption + hashtags + an image scene from the persona, then render
    // the photo.
    const built = await gemini.generatePostContent({
      persona: {
        ...persona,
        displayName: persona.displayName || inf.name,
        niche: persona.niche || inf.niche,
      },
    });
    const image = await gemini.generateInfluencerImage({
      prompt: built.imagePrompt,
      influencerId: inf.id,
      label: "post",
      frameAsSelfie: built.shotType !== "scene",
      referenceImage: inf.image_url || null,
    });
    const hashtagLine = built.hashtags.map((h) => `#${h}`).join(" ");

    // Persist as a draft ("ready" = generated, not yet published) so it can be
    // published by id after review.
    const item = await repo.content.create({
      influencerId: inf.id,
      topic: built.title || null,
      status: "ready",
    });
    await repo.content.update(item.id, {
      title: built.title || null,
      caption: built.caption,
      hashtags: built.hashtags || [],
      image_paths: [image.url],
      meta: {
        altText: built.altText,
        imagePrompt: built.imagePrompt,
        source: "postiz-preview",
      },
    });

    res.json({
      ok: true,
      published: false,
      contentId: item.id,
      imageUrl: image.url,
      caption: built.caption,
      hashtags: built.hashtags,
      hashtagLine,
      altText: built.altText,
    });
  })
);

// Auth required: publish a previously-generated draft post (by contentId)
// through Postiz to the influencer's linked channel. Postiz uploads the draft's
// image and creates the post immediately ("now"). The content row is marked
// "posted" and the published post is recorded; the response includes a link to
// the live channel.
router.post(
  "/post-publish",
  requireAuth,
  asyncH(async (req, res) => {
    const inf = await loadInfluencerForPost(req, res, { requirePublic: true });
    if (!inf) return;
    if (!inf.postiz_integration_id) {
      return res.status(400).json({
        ok: false,
        error:
          "This influencer isn't linked to a Postiz channel yet. Connect a channel before publishing.",
      });
    }
    const contentId = req.body.contentId;
    if (!contentId) {
      return res.status(400).json({ ok: false, error: "contentId is required" });
    }
    const item = await repo.content.get(contentId);
    if (!item || item.influencer_id !== inf.id) {
      return res.status(404).json({ ok: false, error: "post draft not found" });
    }
    const imageRelUrl = item.image_paths?.[0];
    if (!imageRelUrl) {
      return res.status(400).json({ ok: false, error: "draft has no image" });
    }

    const platform = inf.postiz_platform || "instagram";
    const hashtags = item.hashtags || [];
    const hashtagLine = hashtags.map((h) => (h.startsWith("#") ? h : `#${h}`)).join(" ");
    const caption = [item.caption, hashtagLine].filter(Boolean).join("\n\n");

    // The stored image URL is relative (/media/...); make it absolute so Postiz
    // can fetch it.
    const imagePublicUrl = imageRelUrl.startsWith("http")
      ? imageRelUrl
      : `${config.publicBaseUrl}${imageRelUrl}`;

    await repo.content.update(contentId, { status: "posting" });

    // Upload + publish now.
    const media = await postiz.uploadFromUrl(imagePublicUrl);
    const { postId } = await postiz.schedulePost({
      integrationId: inf.postiz_integration_id,
      identifier: platform,
      content: caption,
      date: new Date(),
      media: [media],
      type: "now",
    });

    const integration = await postiz
      .getIntegration(inf.postiz_integration_id)
      .catch(() => null);
    const channelUrl = postiz.profileUrl(integration);

    await repo.content.update(contentId, {
      status: "posted",
      meta: {
        ...(item.meta || {}),
        source: "postiz-publish",
        postizPostId: postId,
        platform,
      },
    });
    try {
      await repo.posts.createPublished({
        influencerId: inf.id,
        contentId,
        postizPostId: postId,
        caption: item.caption,
        platform,
        url: channelUrl,
      });
    } catch (err) {
      console.error("[generate] post-publish persist failed:", err);
    }

    res.json({
      ok: true,
      published: true,
      contentId,
      postizPostId: postId,
      platform,
      imageUrl: imageRelUrl,
      caption: item.caption,
      hashtags,
      hashtagLine,
      channelUrl,
      channelName: integration?.name || integration?.profile || null,
    });
  })
);

// Auth required: persist a generated image to the user's dashboard.
router.post(
  "/save",
  requireAuth,
  asyncH(async (req, res) => {
    const prompt = String(req.body.prompt || "").trim();
    const imageUrl = String(req.body.imageUrl || "").trim();
    const persona =
      req.body.persona && typeof req.body.persona === "object"
        ? req.body.persona
        : {};
    if (!prompt || !imageUrl) {
      return res
        .status(400)
        .json({ ok: false, error: "prompt and imageUrl are required" });
    }
    const generation = await repo.generations.create({
      userId: req.user.id,
      prompt,
      imageUrl,
      persona,
    });
    res.status(201).json({ ok: true, generation });
  })
);

// Auth required: list the user's saved generations for the dashboard.
router.get(
  "/saved",
  requireAuth,
  asyncH(async (req, res) => {
    const generations = await repo.generations.listFor(req.user.id);
    res.json({ ok: true, generations });
  })
);

export default router;
